name: Test release

on:
  push:
    tags:
      - "v*.*.*-beta*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to test_release branch
        uses: actions/checkout@v3
        with:
          ref: test_release

      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: "recursive"

      - name: Setup Node.js 16.18
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn
      - name: Compile release
        run: yarn build:deps

      - name: Setup Qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.ALI_DOCKER_REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_TOKEN }}

      - name: Docker meta info
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ vars.ALI_DOCKER_REGISTRY }}/sky-war/revite-nginx
          tags: |
            type=sha
            type=semver,pattern={{raw}}
      - name: Build and push to Docker Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: "./Dockerfile.test"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
